name: Build and publish to Docker Hub
on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    # strategy:
    #   matrix:
    #     target: [client, client-standalone, server]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          push: true
          target: client
          cache-from: type=registry,ref=14pujan/opal-client:latest
          cache-to: type=inline
          tags: |
            14pujan/opal-client:latest
            14pujan/opal-client:${{ github.event.release.tag_name }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          push: true
          target: client-standalone
          cache-from: type=registry,ref=14pujan/opal-client-standalone:latest
          cache-to: type=inline
          tags: |
            14pujan/opal-client-standalone:latest
            14pujan/opal-client-standalone:${{ github.event.release.tag_name }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          push: true
          target: server
          cache-from: type=registry,ref=14pujan/opal-server:latest
          cache-to: type=inline
          tags: |
            14pujan/opal-server:latest
            14pujan/opal-server:${{ github.event.release.tag_name }}
