name: Build and publish to Docker Hub
on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    strategy:
      matrix:
        target: [client, client-standalone, server]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          push: false
          target: ${{ matrix.target }}
          cache-from: type=registry,ref=authorizon/opal-${{ matrix.target }}:latest
          cache-to: type=inline
          tags: |
            authorizon/opal-${{ matrix.target }}:latest
            authorizon/opal-${{ matrix.target }}:${{ github.sha }}
            authorizon/opal-${{ matrix.target }}:${{ github.event.release.tag_name }}

      - name: Configure and bring up docker compose stack
        run: |
          sed -i docker/docker-compose-example.yml 's/:latest/:${{ github.sha }}'
          echo docker/docker-compose-example.yml
          docker-compose -f docker/docker-compose-example.yml up -d
